version: "2.1"
services:
  api:
    build: .
    container_name: "node-container"
    working_dir: /usr/app
    command:
      [sh, -c, "npm install && pm2-runtime start /usr/app/ecosystem.config.js"]
    environment:
      - DATABASE_URL
      - DATABASE_HOST
      - DATABASE_PORT
      - DATABASE_NAME
      - DATABASE_USER
      - DATABASE_PASS
      - EMAIL_TYPE
      - EMAIL_HOST
      - EMAIL_PORT
      - EMAIL_USER
      - EMAIL_PASS
      - GUEST_MODE
    volumes:
      - ./dev:/usr/app
    ports:
      - "3000:3000"
    depends_on:
      - database
  database:
    image: "mongo"
    container_name: "mongo-container"
    environment:
      - MONGO_INITDB_DATABASE=${DATABASE_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASS}
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
      - ./mongo-volume:/data/db
    ports:
      - "27017-27019:27017-27019"
