version: "2.1"
services:
  api:
    build: .
    container_name: "node-container"
    working_dir: /usr/app
    command:
      [sh, -c, "npm install && pm2-runtime start /usr/app/ecosystem.config.js"]
    environment:
      - DATABASE_URL
      - DATABASE_HOST
      - DATABASE_PORT
      - DATABASE_NAME
      - DATABASE_USER
      - DATABASE_PASS
    volumes:
      - ./dev:/usr/app
    ports:
      - "3000:3000"
